(function() {var implementors = {};
implementors["channel"] = [{"text":"impl&lt;K:&nbsp;Eq + Hash + Clone, M&gt; Drop for Sender&lt;K, M&gt;","synthetic":false,"types":[]},{"text":"impl&lt;K:&nbsp;Eq + Hash + Clone, M&gt; Drop for Receiver&lt;K, M&gt;","synthetic":false,"types":[]}];
implementors["diem_secure_push_metrics"] = [{"text":"impl Drop for MetricsPusher","synthetic":false,"types":[]}];
implementors["diem_swarm"] = [{"text":"impl Drop for InteractiveClient","synthetic":false,"types":[]},{"text":"impl Drop for Process","synthetic":false,"types":[]},{"text":"impl Drop for DiemNode","synthetic":false,"types":[]},{"text":"impl Drop for DiemSwarm","synthetic":false,"types":[]}];
implementors["diem_temppath"] = [{"text":"impl Drop for TempPath","synthetic":false,"types":[]}];
implementors["diem_time_service"] = [{"text":"impl Drop for MockSleep","synthetic":false,"types":[]}];
implementors["diem_trace"] = [{"text":"impl Drop for TraceBlockGuard","synthetic":false,"types":[]}];
implementors["memsocket"] = [{"text":"impl Drop for MemoryListener","synthetic":false,"types":[]}];
if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()