(function() {var implementors = {};
implementors["backup_cli"] = [{"text":"impl AsRef&lt;str&gt; for ShellSafeName","synthetic":false,"types":[]},{"text":"impl AsRef&lt;str&gt; for TextLine","synthetic":false,"types":[]}];
implementors["diem_crypto"] = [{"text":"impl AsRef&lt;[u8; 32]&gt; for HashValue","synthetic":false,"types":[]}];
implementors["diem_network_address"] = [{"text":"impl AsRef&lt;str&gt; for DnsName","synthetic":false,"types":[]}];
implementors["diem_proptest_helpers"] = [{"text":"impl AsRef&lt;Index&gt; for Index","synthetic":false,"types":[]}];
implementors["diem_swarm"] = [{"text":"impl AsRef&lt;Path&gt; for DiemSwarmDir","synthetic":false,"types":[]}];
implementors["diem_temppath"] = [{"text":"impl AsRef&lt;Path&gt; for TempPath","synthetic":false,"types":[]}];
implementors["diem_types"] = [{"text":"impl AsRef&lt;[u8]&gt; for AccountStateBlob","synthetic":false,"types":[]},{"text":"impl AsRef&lt;[u8]&gt; for AuthenticationKey","synthetic":false,"types":[]}];
implementors["functional_tests"] = [{"text":"impl AsRef&lt;Directive&gt; for Directive","synthetic":false,"types":[]},{"text":"impl&lt;T&gt; AsRef&lt;T&gt; for Sp&lt;T&gt;","synthetic":false,"types":[]},{"text":"impl&lt;T&gt; AsRef&lt;T&gt; for LineSp&lt;T&gt;","synthetic":false,"types":[]}];
implementors["invalid_mutations"] = [{"text":"impl AsRef&lt;Index&gt; for CodeUnitBoundsMutation","synthetic":false,"types":[]},{"text":"impl AsRef&lt;Index&gt; for OutOfBoundsMutation","synthetic":false,"types":[]}];
implementors["move_core_types"] = [{"text":"impl AsRef&lt;[u8]&gt; for AccountAddress","synthetic":false,"types":[]},{"text":"impl AsRef&lt;IdentStr&gt; for Identifier","synthetic":false,"types":[]}];
implementors["move_lang"] = [{"text":"impl AsRef&lt;[u8]&gt; for Address","synthetic":false,"types":[]}];
if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()